import type { WritingPost } from "@/types/writing";

export const post: WritingPost = {
  slug: "work-from-ruang",
  title: "Work From Ruang",
  topic: "Life",
  status: "published",
  publishedAt: "2026-07-09",
  image: {
    src: "cover.png",
    alt: "Suasana Work From Ruang di Ruang Tambah, Kota Padang",
  },
  content: [
    "Beberapa bulan terakhir aku kerja dari kamar yang itu-itu aja. Meja sama, kursi sama, pemandangan sama. Kerjaan sih tetap jalan, tapi lama-lama kepala kayak kehabisan udara. Buka laptop jam sembilan pagi, tahu-tahu udah sore, dan aku nggak yakin barusan itu produktif atau cuma sibuk.",
    {
      type: "paragraph",
      segments: [
        "Pas lagi di fase itu, masuk sebuah undangan: ikut Work From Ruang, program dari yang namanya ",
        { type: "mention", entity: "ruang-tambah" },
        " di Kota Padang. Programnya masih dibuka secara internal dan terbatas, jadi yang ikut belum banyak. Aku nggak mikir lama. Ada alasan resmi buat keluar rumah sambil tetap kerja? Ya ambil.",
      ],
    },
    { type: "heading", text: "Sebenarnya Ruang Tambah Itu Apa?" },
    "Buat yang belum familiar, Ruang Tambah itu event space gratis di Kota Padang. Tempatnya sering jadi titik kumpul komunitas dan macam-macam kegiatan kreatif. Kadang diskusi, kadang workshop, kadang sekadar nongkrong yang niatnya produktif. Di kota yang pilihan ruang publiknya nggak banyak, tempat kayak gini lumayan berharga.",
    "Work From Ruang, atau singkatnya WFR, adalah salah satu programnya. Konsepnya sederhana banget: kamu boleh kerja dari Ruang Tambah, dan di sela-sela kerja kamu bisa ketemu, diskusi, atau ngobrol santai sama peserta lain. Nggak ada agenda kaku, nggak ada sesi yang wajib diikuti. Datang, buka laptop, kerja. Sisanya mengalir sendiri.",
    "Jadwalnya tiap Rabu dan Kamis, jam sembilan pagi sampai jam empat sore. Enaknya, peserta bebas datang kapan aja di rentang itu. Mau datang pagi terus cabut habis makan siang, boleh. Mau baru muncul jam dua siang, juga nggak ada yang protes. Buat orang yang jam kerjanya nggak selalu rapi kayak aku, fleksibilitas ini kerasa banget.",
    "Fasilitasnya nggak neko-neko: WiFi dan air minum. Peserta dianjurkan bawa tumbler sendiri, dan menurutku itu masuk akal. Lebih hemat gelas plastik, dan botol minum di sebelah laptop itu entah kenapa bikin kerja kerasa lebih niat. Sisanya ya bawa kerjaan masing-masing.",
    { type: "entityCard", entity: "ruang-tambah" },
    { type: "heading", text: "Hari Pertama Datang" },
    "Rabu pagi aku sampai sekitar jam setengah sepuluh. Niatnya datang jam sembilan teng, tapi ya namanya juga hari pertama. Sampai di sana, udah ada beberapa orang yang duduk dengan laptop masing-masing. Ada yang serius nunduk ke layar, ada yang lagi ngetik sambil sesekali lihat ke luar.",
    "Ruangannya nggak besar-besar amat, tapi lega. Cahayanya cukup, sirkulasi udaranya enak, dan yang paling penting: suasananya tenang tanpa jadi kaku kayak perpustakaan. Orang masih bisa ngobrol pelan tanpa merasa mengganggu. Aku pilih spot dekat jendela, colok charger, sambung WiFi, dan mulai buka kerjaan yang udah aku siapkan dari malamnya.",
    "Satu jam pertama rasanya aneh dalam artian yang bagus. Biasanya jam segitu aku masih perang sama distraksi di kamar. Di sini, begitu duduk, kerjaan langsung jalan. Mungkin karena otak sadar aku udah niat keluar rumah buat ini, jadi nggak enak sendiri kalau ujung-ujungnya cuma scroll.",
    { type: "heading", text: "Ngobrol Sama Orang yang Baru Ketemu" },
    'Bagian yang paling aku suka justru terjadi di jeda-jeda kecil. Waktu ambil air minum, waktu istirahat makan siang, waktu sama-sama ngelurusin punggung. Obrolannya dimulai dari yang paling standar, "lagi ngerjain apa?", terus melebar ke mana-mana.',
    "Pesertanya ternyata campur. Ada yang kerja remote buat perusahaan di luar kota, ada freelancer, ada juga yang masih kuliah dan bawa laporan buat dikerjain. Karena latar belakangnya beda-beda, obrolannya nggak muter di topik yang sama. Aku sempat dapat insight soal cara orang lain ngatur klien, dan gantian cerita soal gimana aku nyusun portfolio.",
    "Yang menarik, semua obrolan itu terjadi tanpa dipaksa. Nggak ada sesi perkenalan formal yang bikin canggung. Kamu bisa milih fokus kerja seharian tanpa ngomong sama siapa pun, dan itu juga nggak apa-apa. Tapi begitu kamu buka obrolan, orang-orangnya welcome. Keseimbangan kayak gitu susah didapat di tempat lain.",
    { type: "heading", text: "Produktif yang Rasanya Beda" },
    "Kerja di rumah dan kerja di ruang bersama itu produktifnya beda jenis. Di rumah, aku bisa kerja lama, tapi batasnya kabur. Kerjaan bocor ke jam makan, ke jam istirahat, kadang sampai malam. Di WFR, ada jam mulai dan ada jam selesai. Jam empat sore, ruangan tutup, kerjaan ikut ditutup. Ternyata batas sesederhana itu bikin kepala jauh lebih tenang.",
    "Ada juga efek yang aku sebut ikut-ikutan fokus. Waktu lihat orang di sebelah lagi serius ngerjain sesuatu, rasanya nggak pantas aja buka tab yang nggak perlu. Nggak ada yang ngawasin, nggak ada yang negur, tapi suasananya yang bikin kamu balik ke kerjaan. Ini jenis tekanan sosial yang sehat menurutku.",
    "Dua hari di sana, daftar kerjaanku kepotong lebih banyak daripada seminggu di kamar. Bukan karena aku tiba-tiba jadi rajin, tapi karena lingkungannya nggak ngasih banyak celah buat kabur.",
    { type: "heading", text: "Buat Pekerja Remote dan Mahasiswa" },
    "Selama ini pilihan tempat kerja di luar rumah biasanya cuma dua: kafe atau perpustakaan. Kafe enak, tapi ada biaya nggak tertulisnya. Minimal beli minum, dan kalau kelamaan duduk mulai muncul rasa nggak enak sama yang punya tempat. Perpustakaan gratis, tapi terlalu sunyi buat kerjaan yang butuh diskusi atau sesekali call.",
    "Tempat kayak Ruang Tambah ngisi ruang kosong di antara keduanya. Gratis, WiFi ada, dan kamu dikelilingi orang yang sama-sama lagi ngerjain sesuatu. Buat pekerja remote, ini semacam kantor tanpa sewa. Buat mahasiswa, ini tempat ngerjain tugas yang suasananya lebih hidup daripada kosan.",
    "Bonusnya yang sering diremehkan: orang-orangnya. Kerja remote atau ngerjain skripsi itu gampang bikin merasa sendirian. Duduk sehari di ruang yang sama dengan orang-orang yang punya ritme serupa, walau nggak banyak ngobrol, rasanya udah cukup buat ngingetin kalau kamu nggak kerja di ruang hampa.",
    { type: "heading", text: "Catatan Sebelum Pulang" },
    "Kamis sore, sebelum pulang, aku sempat mikir kenapa hal sesederhana ini kerasa menyenangkan banget. Jawabannya mungkin karena semuanya nggak dibuat ribet. Nggak ada biaya, nggak ada aturan berlebihan, nggak ada tuntutan apa pun. Cuma ruang, WiFi, air minum, dan orang-orang yang datang dengan niat yang sama.",
    "Karena programnya masih internal dan terbatas, aku belum bisa nyuruh kamu langsung datang minggu depan. Tapi kalau nanti WFR dibuka lebih luas dan kamu tinggal di Padang, menurutku ini layak dicoba, minimal sekali. Bawa laptop, bawa kerjaan, dan jangan lupa bawa tumbler.",
    "Aku sendiri udah mutusin satu hal: selama masih diundang, Rabu dan Kamis ke depan jadwalku udah jelas mau ke mana.",
  ],
};
